title:              Jonathan Nelson
description:        Python Programmer and Data Scientist
author:             Jonathan Nelson
baseurl:            "/"
url:                "https://jonathannelson.io"

# Social Profiles
twitter_username:   NelsonEcon16
github_username:    jnelson16
linkedin_username:  jonathan-nelson-3056a462

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-175200606-1

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
